version: '3'
services:
  hbase:
    image: bde2020/hbase-standalone:1.0.0-hbase1.2.6
    container_name: hbase
    ports:
      - 6000:6000
      - 6010:6010
      - 6020:6020
      - 6030:6030
      - 2888:2888
      - 3888:3888
      - 2181:2181

  notebooks:
    image: playniuniu/jupyter-pandas:latest
    ports:
      - "8888:8888"
    volumes: 
      - ./scripts:/app
    depends_on:
      - hbase